Repository short-d/fluent, pull requests merged in 2020-06, with the labels that each got.

#4 Add issue template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/refactor.md
Labels: size/M

#5 added pull request template
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: size/XS

#6 Configure prettier stylelint
  .prettierrc.json
  .stylelintrc
  package.json
  tslint.json
Labels: size/M

#7 Add Yarn.lock
  example/yarn.lock
  yarn.lock
Labels: enhancement
